"""Added course archive tables

Revision ID: 1cccdbc325f5
Revises: 1c7a3ed9b023
Create Date: 2014-12-10 16:15:34.593220

"""

# revision identifiers, used by Alembic.
revision = '1cccdbc325f5'
down_revision = '1c7a3ed9b023'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
