"""adds skype

Revision ID: 350a011f5d96
Revises: 3f8c98df3fc5
Create Date: 2015-03-12 15:05:43.306583

"""

# revision identifiers, used by Alembic.
revision = '350a011f5d96'
down_revision = '3f8c98df3fc5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archivedcoursemembership', u'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivedcoursemembership', sa.Column(u'id', sa.INTEGER(), server_default="nextval('archivedcoursemembership_id_seq'::regclass)", nullable=False))
    ### end Alembic commands ###
