"""adds skype

Revision ID: 350a011f5d96
Revises: 3f8c98df3fc5
Create Date: 2015-03-12 15:05:43.306583

"""

# revision identifiers, used by Alembic.
revision = '350a011f5d96'
down_revision = '3f8c98df3fc5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
