"""adds skype

Revision ID: 73da0ac9be4
Revises: 350a011f5d96
Create Date: 2015-03-12 15:07:28.009216

"""

# revision identifiers, used by Alembic.
revision = '73da0ac9be4'
down_revision = '350a011f5d96'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('skype', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'skype')
    ### end Alembic commands ###
