#!/usr/bin/env python

from __future__ import print_function
from __future__ import unicode_literals
import argparse
import sys
import os
import logging
from collections import OrderedDict

logger = logging.getLogger('users')

sys.path.insert(0, os.getcwd())

from sqlalchemy import or_, and_

from buddyup.database import User, db
from buddyup import photo
from buddyup.app import app
from buddyup.util import email, delete_user

USER_FILTERS = ["skype", "linkedin", "twitter", "facebook", "bio", "email"]

parser = argparse.ArgumentParser()
parser.add_argument("--verbose", "-v", action="store_true",
                    help="Verbose output")

subparsers = parser.add_subparsers()

def add_filter(parser, name, help_yes=None, help_no=None):
    if help_yes is None:
        help_yes = "only with " + name
    if help_no is None:
        help_no = "only without " + name
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--" + name, action="store_true",
                       help=help_yes)
    group.add_argument("--no-" + name, action="store_true",
                       help=help_no)


def add_user_filters(parser):
    for name in USER_FILTERS:
        add_filter(parser, name)
    add_filter(parser, "photos")

parser_list = subparsers.add_parser("list", help="list users")
add_user_filters(parser_list)

parser_count = subparsers.add_parser("count", help="count users")
add_user_filters(parser_count)

parser_email = subparsers.add_parser("email", help="email formatted names")
add_user_filters(parser_email)
parser_email.add_argument("--single", action="store_true",
                          help="everything on one line")

parser_delete = subparsers.add_parser("delete", help="delete a user")
parser_delete.add_argument("users", nargs="+", help="one or more user names")
parser_delete.add_argument("--dry-run", "-n", action="store_true",
                           help="Show what would be deleted")
parser_delete.add_argument("--force", "-f", action="store_true",
                           help="Do not confirm")


def add_cmd(subparser):
    def add(func):
        subparser.set_defaults(func=func)
        return func
    return add


def filter_contains(args, query, name):
    field = getattr(User, name)
    if getattr(args, name):
        query = query.filter(and_(field != u'', field != None))
    elif getattr(args, "no_" + name):
        query = query.filter(or_(field == u'', field == None))
    return query


def user_filter(args):
    query = User.query
    if args.photos:
        query = query.filter_by(has_photos=True)
    elif args.no_photos:
        query = query.filter_by(has_photos=False)

    for name in USER_FILTERS:
        query = filter_contains(args, query, name)
    return query


@add_cmd(parser_list)
def cmd_list(args):
    query = user_filter(args)
    for user in query.all():
        print(user.user_name)


@add_cmd(parser_count)
def cmd_count(args):
    query = user_filter(args)
    print(query.count())


@add_cmd(parser_email)
def cmd_email(args):
    query = user_filter(args)
    addresses = []
    for user in query.all():
        addresses.append(u"{name} <{address}>".format(
            name=user.full_name or user.user_name,
            address=email(user)))
    if args.single:
        seperator = ', '
    else:
        seperator = "\n"
    print(seperator.join(addresses))


@add_cmd(parser_delete)
def cmd_delete(args):
    # Use an ordered dict to avoid double 
    records = OrderedDict()
    not_found = False
    for user_name in args.users:
        record = User.query.filter_by(user_name=user_name).first()
        if record is None:
            logger.error("user %s does not exist", user_name)
            not_found = True
        records[user_name] = record
    if not_found:
        return

    if args.dry_run:
        delete_dry_run(args, records)
    else:
        delete_real(args, records)


def delete_dry_run(args, records):
    for user_name, user_record in records.items():
        full_name = user_record.full_name
        print("Would delete user '%s' with full name '%s'" %
              (user_name, full_name))


def delete_real(args, records):
    if not args.force:
        logger.info("Would delete %s", ', '.join(records.keys()))
        response = raw_input("Delete %d users (y/N)? " % len(records))
        if response.lower() != 'y':
            return
    try:
        for user_name, user_record in records.items():
            full_name = user_record.full_name
            delete_user(user_record)
            logger.info("Deleted user %s with full name %s",
                        user_name, full_name)
    except:
        db.session.rollback()
        raise
    else:
        db.session.commit()


def main():
    args = parser.parse_args()
    log_handler = logging.StreamHandler()
    logger.addHandler(log_handler)
    if args.verbose:
        logger.setLevel(logging.INFO)
        app.logger.addHandler(log_handler)
    else:
        logger.setLevel(logging.ERROR)
    args.func(args)
    

if __name__ == '__main__':
    main()